#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  5 18:53:53 2018

@author: mc
"""

import os
import subprocess


bashCommand = "ssh cocca@bigdatadb "+\
      "hdfs dfs -cat "+\
      "Simulator/output/Simulation_6/"+\
      "car2go_Needed_max-time_9_4_50_1000000_100_0.txt"

process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
strOutput =  output.decode("utf-8") 

path = "./"
newFileName = city+filename()

f = open(path+newFileName)
f.wrtie(strOutput)
f.close()

